# Site settings
title: gf&zjの盗梦空间
email: gf@gfzj.us
description: 记录工作学习和生活。让世界了解我们。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gfzj.us" # the base hostname & protocol for your site
twitter_username: thinkphone
github_username:  100apps

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"
timezone: 'Asia/Shanghai'
