# Site settings
title: gf&zjの盗梦空间
email: gf@gfzj.us
description: 记录工作学习和生活。让世界了解我们。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gfzj.us" # the base hostname & protocol for your site
twitter_username: thinkphone
github_username:  100apps

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"
timezone: 'Asia/Shanghai'

authors:
 zj:
  display_name: Jing Zhou
  email: zj@gfzj.us
  note: 大数据 / Java / spark / scala @<a href="http://www.gridsum.com/">国双科技</a>
 gf:
  display_name: Guangfeng Liu
  email: gf@gfzj.us
  note: 一枚普通的码农@阿里巴巴

plugins: [jekyll-paginate]
